// Generated by gencpp from file learning_topic/Animal.msg
// DO NOT EDIT!


#ifndef LEARNING_TOPIC_MESSAGE_ANIMAL_H
#define LEARNING_TOPIC_MESSAGE_ANIMAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_topic
{
template <class ContainerAllocator>
struct Animal_
{
  typedef Animal_<ContainerAllocator> Type;

  Animal_()
    : name()
    , num_calls(0)
    , sound()  {
    }
  Animal_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , num_calls(0)
    , sound(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _num_calls_type;
  _num_calls_type num_calls;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sound_type;
  _sound_type sound;




  typedef boost::shared_ptr< ::learning_topic::Animal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_topic::Animal_<ContainerAllocator> const> ConstPtr;

}; // struct Animal_

typedef ::learning_topic::Animal_<std::allocator<void> > Animal;

typedef boost::shared_ptr< ::learning_topic::Animal > AnimalPtr;
typedef boost::shared_ptr< ::learning_topic::Animal const> AnimalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_topic::Animal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_topic::Animal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace learning_topic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'learning_topic': ['/home/ubuntu/dogkin_ws/src/learning_topic/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::Animal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::Animal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_topic::Animal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_topic::Animal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::Animal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::Animal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_topic::Animal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5d670d018241960bce850ba1516dac3";
  }

  static const char* value(const ::learning_topic::Animal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5d670d018241960ULL;
  static const uint64_t static_value2 = 0xbce850ba1516dac3ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_topic::Animal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_topic/Animal";
  }

  static const char* value(const ::learning_topic::Animal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_topic::Animal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
uint8 num_calls\n\
string sound\n\
\n\
";
  }

  static const char* value(const ::learning_topic::Animal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_topic::Animal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.num_calls);
      stream.next(m.sound);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Animal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_topic::Animal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_topic::Animal_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "num_calls: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_calls);
    s << indent << "sound: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sound);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_TOPIC_MESSAGE_ANIMAL_H
